name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint with zero warnings
      run: npm run lint -- --max-warnings 0
    
    - name: Run TypeScript type checking
      run: npm run typecheck
    
    - name: Run build (same as Vercel)
      run: npm run build
      env:
        SKIP_ENV_VALIDATION: 1
    
    - name: Check for build artifacts
      run: |
        if [ ! -d ".next" ]; then
          echo "Build failed - no .next directory found"
          exit 1
        fi
        echo "Build successful - .next directory exists"